# Per-node overrides. Shared vars live in deploy/stage/common-values-ampc-hnsw.yaml
# and are deep-merged with this map by Helm.
env:
  SMPC__SERVICE__SERVICE_NAME: "hnsw-service-0"
  SMPC__SERVER_COORDINATION__PARTY_ID: "0"
  SMPC__SERVER_COORDINATION__NODE_HOSTNAMES: '["0.0.0.0","node.1.stage.hnsw.worldcoin.dev","node.2.stage.hnsw.worldcoin.dev"]'
  SMPC__DB_CHUNKS_BUCKET_NAME: "ampc-hnsw-db-exporter-store-node-0-stage--eun1-az3--x-s3"
  SMPC__SERVICE__METRICS__PREFIX: "hnsw-0"

initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "hnsw-mpc-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "0"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".stage.hnsw.worldcoin.dev --query "HostedZones[0].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for HNSW pod",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "node.$PARTY_ID.stage.hnsw.worldcoin.dev",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$POD_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"

attachSecurityGroupPolicy:
  enabled: true
  groupIds:
  - sg-009f4095359514cf3 # smpc0-stage ampc-hnsw pod sg
