env:
  - name: ENV
    value: stage
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_HNSW_URL
        name: application
  - name: SERVICE_NAME
    value: ampc-hnsw-db-exporter-0
  - name: AWS_REGION
    value: eu-north-1
  - name: GIN_MODE
    value: release
  - name: EXPORT_S3_BUCKET_NAME
    value: "ampc-hnsw-db-exporter-store-node-0-stage--eun1-az3--x-s3"
  - name: NODE_ID
    value: "0"


attachSecurityGroupPolicy:
  enabled: true
  groupIds:
    - sg-0fb6ff6a5a73007dd # smpc0-stage ampc-hnsw-db-exporter pod sg
