# Per-node overrides; shared vars live in common-values-anon-stats-server.yaml.
env:
  SMPC__SERVICE__SERVICE_NAME: "anon-stats-server-smpcv2-2"
  SMPC__SERVER_COORDINATION__PARTY_ID: "2"
  SMPC__SERVER_COORDINATION__NODE_HOSTNAMES: '["anon-stats-server.1.smpcv2.worldcoin.org","anon-stats-server.2.smpcv2.worldcoin.org","0.0.0.0"]'
  SMPC__SERVICE__METRICS__PREFIX: "anon-stats-server-smpcv2-2"
  SMPC__HEALTHCHECK_PORTS: '["3000","3000","3000"]'

nodeSelector:
  kubernetes.io/arch: amd64
  workload: "anon-stats-server"

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "anonStatsServer"
    effect: "NoSchedule"

initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "anon-stats-server-smpcv2-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "3"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".smpcv2.worldcoin.org --query "HostedZones[0].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for anon-stats-server-smpcv2 pod",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "anon-stats-server.$PARTY_ID.smpcv2.worldcoin.org",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$POD_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"
