apiVersion: v1
kind: Pod
metadata:
  name: db-cleaner
  namespace: ampc-hnsw
spec:
  securityContext:
    runAsUser: 0
  containers:
    - securityContext:
        allowPrivilegeEscalation: false
      name: db-cleaner
      image: postgres
      imagePullPolicy: Always
      command: [ "/bin/bash" ]
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi

