apiVersion: v1
kind: Pod
metadata:
  name: db-cleaner
  namespace: ampc-hnsw
spec:
  nodeSelector:
    beta.kubernetes.io/instance-type: t3.medium
  securityContext:
    runAsUser: 0
  containers:
    - name: db-cleaner
      image: postgres
      imagePullPolicy: Always
      command: [ "/bin/bash" ]
      args: [ "-c", "while true; do ping localhost; sleep 60; done" ]
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
