services:
  dev_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=kms,s3,secretsmanager,sqs,sns
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    healthcheck:
      test: >-
        sleep 10 &&
        awslocal sqs list-queues && 
        awslocal s3 ls && 
        awslocal kms list-keys
      interval: 5s
      timeout: 25s
      retries: 10

    volumes:
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh

  hawk_participant_0:
    image: iris-mpc-hawk:latest
    env_file:
      - .test.env
      - .test.hawk0.env
    depends_on:
      localstack:
        condition: service_healthy
      dev_db:
        condition: service_healthy
    ports:
      - "127.0.0.1:4000:4000"
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      retries: 10
    entrypoint: ./run-server-docker.sh 0 --init-servers

  hawk_participant_1:
    image: iris-mpc-hawk:latest
    env_file:
      - .test.env
      - .test.hawk1.env
    depends_on:
      localstack:
        condition: service_healthy
      dev_db:
        condition: service_healthy
    ports:
      - "127.0.0.1:4001:4001"
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      retries: 10
    entrypoint: ./run-server-docker.sh 1
#    entrypoint: tail -f /dev/null

  hawk_participant_2:
    image: iris-mpc-hawk:latest
    env_file:
      - .test.env
      - .test.hawk2.env
    depends_on:
      localstack:
        condition: service_healthy
      dev_db:
        condition: service_healthy
    ports:
      - "127.0.0.1:4002:4002"
      - "3002:3002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      retries: 10
    entrypoint: ./run-server-docker.sh 2

  iris_mpc_client:
    image: iris-mpc-hawk:latest
    entrypoint: tail -f /dev/null
    env_file:
      - .test.env
    environment:
      - SMPC__DATABASE__URL=postgres://postgres:postgres@dev_db:5432/SMPC_dev_2
      - SMPC__PARTY_ID=2
      - SMPC__HAWK_SERVER_HEALTHCHECK_PORT=3002
    command: tail -f /dev/null
    depends_on:
      hawk_participant_0:
        condition: service_healthy
      hawk_participant_1:
        condition: service_healthy
      hawk_participant_2:
        condition: service_healthy
