FROM ghcr.io/worldcoin/iris-mpc-cpu:113465769188c52ebe4a51479a570ad46c5cfdf6-arm64

USER 0
COPY scripts/tools/init-single-db.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh

USER 65534
ENTRYPOINT ["/bin/entrypoint.sh"]
