FROM nginx:1.19-alpine

# Copy your entrypoint script into the image
COPY scripts/nginx_docker_entrypoint.sh /usr/local/bin/entrypoint.sh

# Make sure the entrypoint script is executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Optionally, set the command
CMD ["nginx", "-g", "daemon off;"]
