FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

ARG ARCHITECTURE
ENV ARCHITECTURE=$ARCHITECTURE

RUN apt-get update && apt-get install -y ca-certificates curl unzip

COPY ./scripts/no-op.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh

USER 65534

ENTRYPOINT ["/bin/entrypoint.sh"]
