# Set base image.
FROM  ubuntu:22.04 AS build-image

WORKDIR /src

# Install pre-requisites.
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    libssl-dev \
    texinfo \
    libcap2-bin \
    pkg-config \
    git \
    devscripts \
    debhelper \
    ca-certificates \
    protobuf-compiler \
    wget

# Install rust.
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
ENV RUSTUP_HOME="/root/.rustup"
ENV CARGO_HOME="/root/.cargo"
RUN rustup toolchain install 1.85.0
RUN rustup default 1.85.0
RUN rustup component add cargo
RUN cargo install cargo-build-deps
RUN cargo install cargo-edit

FROM build-image AS build-app
WORKDIR /src
COPY . .

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

# Install self-signed certificates.
RUN apt-get update && apt-get install -y ca-certificates awscli curl
COPY certs /usr/local/share/ca-certificates/
RUN update-ca-certificates

# Install software assets.
COPY --from=build-app /src /src
COPY scripts/run-tests-hnsw-e2e.sh .

# Set nobody user.
USER 65534

# ENTRYPOINT ["./run-tests-hnsw-e2e.sh"]
