# Set base image.
FROM public.ecr.aws/docker/library/rust:1.89-slim-bullseye AS build-image

# Install pre-requisites.
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    libssl-dev \
    texinfo \
    libcap2-bin \
    pkg-config \
    git \
    devscripts \
    debhelper \
    ca-certificates \
    protobuf-compiler \
    wget \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install root certificate.
RUN apt-get update && apt-get install -y \
    ca-certificates \
    awscli \
    curl
COPY certs /usr/local/share/ca-certificates/
RUN update-ca-certificates

# Install non-root user to run tests.
RUN useradd -m -u 1000 -s /bin/bash runner

# Install software assets.
FROM build-image AS build-app
WORKDIR /src/iris-mpc
COPY . .

# Set working directory.
WORKDIR /

# Set entrypoint for the container
# ENTRYPOINT ["/src/iris-mpc/scripts/run-tests-hnsw-e2e.sh"]
