services:
  dev_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=kms,s3,secretsmanager,sqs,sns
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh

  hawk_participant_0:
    build:
      context: .
      dockerfile: Dockerfile.hawk
    env_file:
      - .test.env
    environment:
      - SMPC__DATABASE__URL=postgres://postgres:postgres@dev_db:5432/SMPC_dev_0
      - SMPC__PARTY_ID=0
      - SMPC__HAWK_SERVER_HEALTHCHECK_PORT=3000
    depends_on:
      dev_db:
        condition: service_healthy
    ports:
      - "4000:4000"
      - "3000:3000"

  hawk_participant_1:
    build:
      context: .
      dockerfile: Dockerfile.hawk
    env_file:
      - .test.env
    environment:
      - SMPC__DATABASE__URL=postgres://postgres:postgres@dev_db:5432/SMPC_dev_1
      - SMPC__PARTY_ID=1
      - SMPC__HAWK_SERVER_HEALTHCHECK_PORT=3001
    depends_on:
      dev_db:
        condition: service_healthy
    ports:
      - "4001:4001"
      - "3001:3001"

  hawk_participant_2:
    build:
      context: .
      dockerfile: Dockerfile.hawk
    env_file:
      - .test.env
    environment:
      - SMPC__DATABASE__URL=postgres://postgres:postgres@dev_db:5432/SMPC_dev_2
      - SMPC__PARTY_ID=2
      - SMPC__HAWK_SERVER_HEALTHCHECK_PORT=3002
    depends_on:
      dev_db:
        condition: service_healthy
    ports:
      - "4002:4002"
      - "3002:3002"
