apiVersion: v1
kind: Pod
metadata:
  name: gpu-iris-mpc
  namespace: gpu-iris-mpc
spec:
  hostNetwork: true
  serviceAccountName: gpu-iris-mpc  # Add this line
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "gpuGroup"
      effect: "NoSchedule"
  imagePullSecrets:
    - name: github-secret
  securityContext:
    runAsUser: 0
  containers:
    - name: gpu-iris-mpc
      image: ghcr.io/worldcoin/gpu-iris-mpc-debug:2b1a5adf8aebc6a0917f591ec2cc364d5ea5d346
      imagePullPolicy: Always
      command: [ "/bin/bash" ]
      args: [ "-c", "while true; do ping localhost; sleep 60; done" ]
      resources:
        limits:
          nvidia.com/gpu: 1
          vpc.amazonaws.com/efa: 1
        requests:
          nvidia.com/gpu: 1
          vpc.amazonaws.com/efa: 1
      ports:
        - containerPort: 3000
