services:
  new-db-1:
    image: postgres:16
    ports:
      - "6200:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  new-db-2:
    image: postgres:16
    ports:
      - "6201:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  new-db-3:
    image: postgres:16
    ports:
      - "6202:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  new-db-4:
    image: postgres:16
    ports:
      - "6203:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  new-db-5:
    image: postgres:16
    ports:
      - "6204:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  new-db-6:
    image: postgres:16
    ports:
      - "6205:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=secretsmanager,s3
      - DEFAULT_REGION=us-east-1
