image: "ghcr.io/worldcoin/iris-mpc-database-exporter:d2a0a3c45922e448a8b6159af5dbcba04651cec7@sha256:d601349b6266470a73cdfb3928e4b65b8f0a7d58a29b88794ed6510d90c6112a"

replicaCount: 1

environment: dev

schedule: "0 10 * * *"

# this is needed to prevent the job from restarting if it fails
backoffLimit: 0

args:
  - "export-db"
  - "--export-mode=COMPLETE_EXPORT"
  - "--export-format=binary"
  - "--export-output=s3"
  - "--batch-size=16000"
  - "--parallelism=60"
  - "--output-folder=hnsw_even_odd_with_version_id_output_16k"

imagePullSecrets:
  - name: github-secret

resources:
  limits:
    cpu: 7
    memory: 31Gi
  requests:
    cpu: 4
    memory: 25Gi

nodeSelector:
  kubernetes.io/arch: amd64

# If it is time for a new Job run and the previous Job run hasn't finished yet, the CronJob replaces the currently running Job run with a new Job run
concurrencyPolicy: Replace
