schema_name = "SMPC"
environment = "dev"
party_id = 1
requests_queue_url = "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/smpcv2-1-dev.fifo"
results_topic_arn = "arn:aws:sns:us-east-1:000000000000:iris-mpc-results.fifo"
kms_key_arns = '["arn:aws:kms:us-east-1:000000000000:key/00000000-0000-0000-0000-000000000000","arn:aws:kms:us-east-1:000000000000:key/00000000-0000-0000-0000-000000000001","arn:aws:kms:us-east-1:000000000000:key/00000000-0000-0000-0000-000000000002"]'
processing_timeout_secs = 60
startup_sync_timeout_secs = 300
public_key_base_url = ""
shares_bucket_name = "wf-smpcv2-dev-sns-requests"
clear_db_before_init = false
init_db_size = 0
max_db_size = 10000
max_batch_size = 0
heartbeat_interval_secs = 2
heartbeat_initial_retries = 10
fake_db_size = 0
return_partial_results = false
disable_persistence = false
enable_debug_timing = false
node_hostnames = '["127.0.0.1", "127.0.0.1", "127.0.0.1"]'
service_ports = '["4000", "4001", "4002"]'
healthcheck_ports = '["3000", "3001", "3002"]'
http_query_retry_delay_ms = 1000
shutdown_last_results_sync_timeout_secs = 60
image_name = ""
enable_s3_importer = false
db_chunks_bucket_name = ""
load_chunks_parallelism = 32
db_load_safety_overlap_seconds = 60
db_chunks_folder_name = ""
load_chunks_buffer_size = 0
load_chunks_max_retries = 5
load_chunks_initial_backoff_ms = 200
fixed_shared_secrets = false
luc_enabled = false
luc_lookback_records = 0
luc_serial_ids_from_smpc_request = false
match_distances_buffer_size = 256
match_distances_buffer_size_extra_percent = 20
n_buckets = 10
enable_sending_anonymized_stats_message = false
enable_sending_mirror_anonymized_stats_message = false
enable_reauth = false
enable_reset = false
hnsw_schema_name_suffix = "_hnsw"
gpu_schema_name_suffix = ""
hawk_request_parallelism = 1
hawk_connection_parallelism = 16
hawk_server_healthcheck_port = 3001
hnsw_param_ef_constr = 320
hnsw_param_M = 256
hnsw_param_ef_search = 256
max_deletions_per_batch = 100
enable_modifications_sync = false
enable_modifications_replay = false
sqs_sync_long_poll_seconds = 10
hawk_server_deletions_enabled = false
hawk_server_reauths_enabled = false
hawk_server_resets_enabled = false
full_scan_side = "Left"
full_scan_side_switching_enabled = true
batch_polling_timeout_secs = 1
sqs_long_poll_wait_time = 10
batch_sync_polling_timeout_secs = 10

[service]
service_name = "smpcv2-server-dev"

[database]
url = "postgres://postgres:postgres@dev_db:5432/SMPC_dev_1"
migrate = false
create = false
load_parallelism = 8

[cpu_database]
url = "postgres://postgres:postgres@dev_db:5432/SMPC_dev_1"
migrate = true
create = true
load_parallelism = 8

[aws]
endpoint = "localstack:4566"
region = "us-east-1"
