env:
  - name: RUST_LOG
    value: "info"

  - name: RUST_BACKTRACE
    value: "full"

  - name: SMPC__PPROF_FLAME_ONLY
    value: "true"

  - name: SMPC__ENABLE_PPROF_PER_BATCH
    value: "true"

  # Optional overrides (uncomment/customize as needed)
  - name: SMPC__PPROF_S3_BUCKET
    value: "wf-smpcv2-dev-hnsw-performance-reports"

  - name: SMPC__PPROF_PREFIX
    value: "dev/hnsw"

  - name: SMPC__PPROF_SECONDS
    value: "180"

  - name: SMPC__PPROF_FREQUENCY
    value: "49"

  # Use Pod annotation as run-id (set via `podAnnotations` above)
  - name: SMPC__PPROF_RUN_ID
    valueFrom:
      fieldRef:
        fieldPath: metadata.annotations['loadtest/run-id']

  - name: SMPC__ENVIRONMENT
    value: "dev"

  - name: SMPC__SERVICE__SERVICE_NAME
    value: "hnsw-service-2"

  - name: SMPC__PARTY_ID
    value: "2"

  - name: SMPC__CPU_DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_HNSW_FROM_SNAPSHOT_URL
        name: application

  - name: SMPC__MAX_DB_SIZE
    value: "2000000"

  - name: SMPC__MAX_BATCH_SIZE
    value: "32"

  - name: SMPC__BATCH_SYNC_POLLING_TIMEOUT_SECS
    value: "30"

  - name: SMPC__PROCESSING_TIMEOUT_SECS
    value: "1240"

  - name: SMPC__HAWK_REQUEST_PARALLELISM
    value: "1024"

  - name: SMPC__HAWK_CONNECTION_PARALLELISM
    value: "48"

  - name: SMPC__HAWK_STREAM_PARALLELISM
    value: "32"

  - name: SMPC__DISABLE_PERSISTENCE
    value: "false"

  - name: SMPC__MATCH_DISTANCES_BUFFER_SIZE
    value: "512"

  - name: SMPC__N_BUCKETS
    value: "16"

  - name: SMPC__ENABLE_SENDING_ANONYMIZED_STATS_MESSAGE
    value: "false"

  - name: SMPC__HAWK_SERVER_REAUTHS_ENABLED
    value: "true"

  - name: SMPC__HAWK_SERVER_RESETS_ENABLED
    value: "true"

  - name: SMPC__HAWK_SERVER_DELETIONS_ENABLED
    value: "true"

  - name: SMPC__LUC_ENABLED
    value: "true"

  - name: SMPC__LUC_LOOKBACK_RECORDS
    value: "5"

  - name: SMPC__LUC_SERIAL_IDS_FROM_SMPC_REQUEST
    value: "false"

  - name: SMPC__AWS__REGION
    value: "eu-central-1"

  - name: SMPC__SERVICE_PORTS
    value: '["4000","4001","4002"]'

  - name: SMPC__HAWK_SERVER_HEALTHCHECK_PORT
    value: '3000'

  - name: SMPC__NODE_HOSTNAMES
    value: '["node.0.dev.hnsw.worldcoin.dev","node.1.dev.hnsw.worldcoin.dev","0.0.0.0"]'

  - name: SMPC__SHARES_BUCKET_NAME
    value: "wf-smpcv2-dev-sns-requests-v2"

  - name: SMPC__ENABLE_S3_IMPORTER
    value: "false"

  - name: SMPC__DB_CHUNKS_BUCKET_NAME
    value: "ampc-hnsw-db-exporter-store-node-2-dev--eun1-az3--x-s3"

  - name: SMPC__DB_CHUNKS_FOLDER_NAME
    value: "hnsw_even_odd_with_version_id_output_16k"

  - name: SMPC__LOAD_CHUNKS_PARALLELISM
    value: "64"

  - name: SMPC__LOAD_CHUNKS_BUFFER_SIZE
    value: "1024"

  - name: SMPC__REQUESTS_QUEUE_URL
    valueFrom:
      secretKeyRef:
        key: SQS_URL
        name: application

  - name: SMPC__RESULTS_TOPIC_ARN
    valueFrom:
      secretKeyRef:
        key: SNS_RESULTS_ARN
        name: application

  - name: SMPC__KMS_KEY_ARNS
    valueFrom:
      secretKeyRef:
        key: KMS_KEYS
        name: application

  - name: SMPC__HEARTBEAT_INITIAL_RETRIES
    value: "65"

  - name: SMPC__SERVICE__METRICS__HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

  - name: SMPC__SERVICE__METRICS__PORT
    value: "8125"

  - name: SMPC__SERVICE__METRICS__QUEUE_SIZE
    value: "5000"

  - name: SMPC__SERVICE__METRICS__BUFFER_SIZE
    value: "256"

  - name: SMPC__SERVICE__METRICS__PREFIX
    value: "hnsw-2"

  - name: SMPC__IMAGE_NAME
    value: $(IMAGE_NAME)

  - name: SMPC__ENABLE_MODIFICATIONS_SYNC
    value: "true"

  - name: SMPC__ENABLE_MODIFICATIONS_REPLAY
    value: "false"

  - name: SMPC__TLS__PRIVATE_KEY
    value: "/etc/ssl/private/key.pem"

  - name: SMPC__TLS__LEAF_CERT
    value: "/etc/ssl/private/certificate.crt"

  - name: SMPC__TLS__ROOT_CERTS
    value: '["/usr/local/share/ca-certificates/ca_party_dev_0.crt", "/usr/local/share/ca-certificates/ca_party_dev_1.crt", "/usr/local/share/ca-certificates/ca_party_dev_2.crt"]'

  - name: SMPC__TLS__WITH_NGINX_SIDECAR
    value: "false"

  - name: SMPC__TLS__CLIENT_ONLY_TLS
    value: "false"

initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "hnsw-mpc-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "2"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".dev.hnsw.worldcoin.dev --query "HostedZones[0].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for HNSW pod",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "node.$PARTY_ID.dev.hnsw.worldcoin.dev",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$POD_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"

attachSecurityGroupPolicy:
  enabled: true
  groupIds:
  - sg-0f4a0e8452af84495 # smpc2-dev ampc-hnsw pod sg
