-- Step 1: Create a new table with the desired schema and desired IDENTITY property for id
CREATE TABLE irises_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    code BYTEA,
    mask BYTEA
);

-- Step 2: Copy the data from the old table to the new table (excluding the id column, letting it auto-generate)
INSERT INTO irises_new (code, mask)
SELECT code, mask FROM irises
ORDER BY id;

-- Step 3: Drop the old table
DROP TABLE irises;

-- Step 4: Rename the new table to the old table's name
ALTER TABLE irises_new RENAME TO irises;
