--- store genesis graph checkpoint metadata snapshots
CREATE TABLE IF NOT EXISTS genesis_graph_checkpoint
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s3_key text NOT NULL,
    last_indexed_iris_id BIGINT NOT NULL,
    last_indexed_modification_id BIGINT NOT NULL,
    blake3_hash TEXT NOT NULL
);
