CREATE TABLE IF NOT EXISTS hawk_graph_checkpoint
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s3_key text NOT NULL,
    graph_mutation_id BIGINT NOT NULL,
    blake3_hash TEXT NOT NULL,
    graph_version INT NOT NULL
);
