image: "ghcr.io/worldcoin/iris-mpc-database-exporter:v0.31.11@sha256:0dcd552aa455b6af8064529298eab4787bbfa0c539a5bcd01e009b408ec14149"

replicaCount: 0

environment: prod

schedule: "30 12 * * *"

# this is needed to prevent the job from restarting if it fails
backoffLimit: 0

args:
  - "export-db"
  - "--export-mode=COMPLETE_EXPORT"
  - "--export-format=binary"
  - "--export-output=s3"
  - "--batch-size=16000"
  - "--parallelism=60"
  - "--output-folder=hnsw_even_odd_with_version_id_output_16k"

imagePullSecrets:
  - name: github-secret

resources:
  limits:
    cpu: 7
    memory: 31Gi
  requests:
    cpu: 4
    memory: 25Gi

nodeSelector:
  kubernetes.io/arch: amd64

# If it is time for a new Job run and the previous Job run hasn't finished yet, the CronJob replaces the currently running Job run with a new Job run
concurrencyPolicy: Replace
