image: "ghcr.io/worldcoin/iris-mpc-database-exporter:v0.31.8@sha256:fd14a8270fd78f285b45f30df551f7be49a42b2f9cd928b5536b35977dfc14ea"

replicaCount: 1

environment: prod

schedule: "0 7,19 * * *"

backoffLimit: 0

args:
  - "export-db"
  - "--export-mode=COMPLETE_EXPORT"
  - "--export-format=binary"
  - "--export-output=s3"
  - "--batch-size=16000"
  - "--parallelism=96"
  - "--output-folder=even_odd_with_version_id_output_16k_rerandomized"

imagePullSecrets:
  - name: github-secret

resources:
  limits:
    cpu: 7
    memory: 26Gi
  requests:
    cpu: 7
    memory: 26Gi

nodeSelector:
  kubernetes.io/arch: amd64

# If it is time for a new Job run and the previous Job run hasn't finished yet, the CronJob replaces the currently running Job run with a new Job run
concurrencyPolicy: Replace
