image: "ghcr.io/worldcoin/iris-mpc-db-exporter:v0.31.0@sha256:db0fcf30da61b526e34e5e9081ca59858ddf00d506b08019734c0a3d2dd57007"

replicaCount: 1

environment: prod

schedule: "0 7,19 * * *"

backoffLimit: 0

args:
  - "export-db"
  - "--export-mode=COMPLETE_EXPORT"
  - "--export-format=binary"
  - "--export-output=s3"
  - "--batch-size=16000"
  - "--parallelism=96"
  - "--output-folder=even_odd_with_version_id_output_16k_rerandomized"

imagePullSecrets:
  - name: github-secret

resources:
  limits:
    cpu: 7
    memory: 26Gi
  requests:
    cpu: 7
    memory: 26Gi

nodeSelector:
  kubernetes.io/arch: amd64

# If it is time for a new Job run and the previous Job run hasn't finished yet, the CronJob replaces the currently running Job run with a new Job run
concurrencyPolicy: Replace
