image: "ghcr.io/worldcoin/iris-mpc-database-exporter:1df123cf6a992a085511c56815c6cec3f5a819fa@sha256:e257b2d30a3aa91461c4a46171d7e89dbf9463aed81f6d3c6233b138cc763b94"

replicaCount: 1

environment: prod

schedule: "0 7,19 * * *"

backoffLimit: 0

args:
  - "export-db"
  - "--export-mode=COMPLETE_EXPORT"
  - "--export-format=binary"
  - "--export-output=s3"
  - "--batch-size=16000"
  - "--parallelism=96"
  - "--output-folder=even_odd_with_version_id_output_16k_rerandomized"

imagePullSecrets:
  - name: github-secret

resources:
  limits:
    cpu: 7
    memory: 26Gi
  requests:
    cpu: 7
    memory: 26Gi

nodeSelector:
  kubernetes.io/arch: amd64

# If it is time for a new Job run and the previous Job run hasn't finished yet, the CronJob replaces the currently running Job run with a new Job run
concurrencyPolicy: Replace
