apiVersion: v1
kind: Pod
metadata:
  name: smpcv2-signup-service-helper
  namespace: signup-service
spec:
  serviceAccountName: signup-service-worker  # Add this line
  imagePullSecrets:
    - name: github-secret
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: smpcv2-signup-service-helper
      image: ghcr.io/worldcoin/gpu-iris-mpc:3b21c20235536b392aef3119ddfc5014daf3d66c
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault  # or Localhost if you have a local profile
        capabilities:
          drop:
            - ALL
      imagePullPolicy: Always
      command: [ "/bin/bash" ]
      args: [ "-c", "while true; do ping localhost; sleep 60; done" ]
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
