apiVersion: v1
kind: Pod
metadata:
  name: smpcv2-signup-service-helper
  namespace: signup-service
spec:
  serviceAccountName: signup-service-worker  # Add this line
  imagePullSecrets:
    - name: github-secret
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: smpcv2-signup-service-helper
      image: ghcr.io/worldcoin/gpu-iris-mpc-debug:0510757a9d076c206d9a42eedca639787c44a0a8
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault  # or Localhost if you have a local profile
      imagePullPolicy: Always
      command: [ "/bin/bash" ]
      args: [ "-c", "while true; do ping localhost; sleep 60; done" ]
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 4
          memory: 4Gi
