env:
  - name: RUST_LOG
    value: "info"

  - name: SMPC__ENVIRONMENT
    value: "stage"

  - name: SMPC__SERVICE__SERVICE_NAME
    value: "anon-stats-server-smpcv2-2"

  - name: SMPC__PARTY_ID
    value: "2"

  - name: SMPC__CPU_DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_URL
        name: application

  - name: SMPC__SERVICE_PORTS
    value: '["4000","4001","4002"]'

  - name: SMPC__HEALTHCHECK_PORT
    value: '3000'

  - name: SMPC__NODE_HOSTNAMES
    value: '["anon-stats-server.0.stage.smpcv2.worldcoin.dev","anon-stats-server.1.stage.smpcv2.worldcoin.dev","0.0.0.0"]'

  - name: SMPC__RESULTS_TOPIC_ARN
    valueFrom:
      secretKeyRef:
        key: SNS_RESULTS_ARN
        name: application

  - name: SMPC__HEARTBEAT_INITIAL_RETRIES
    value: "65"

  - name: SMPC__SERVICE__METRICS__HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

  - name: SMPC__SERVICE__METRICS__PORT
    value: "8125"

  - name: SMPC__SERVICE__METRICS__QUEUE_SIZE
    value: "5000"

  - name: SMPC__SERVICE__METRICS__BUFFER_SIZE
    value: "256"

  - name: SMPC__SERVICE__METRICS__PREFIX
    value: "anon-stats-server-smpcv2-2"

  - name: SMPC__IMAGE_NAME
    value: $(IMAGE_NAME)

  - name: SMPC__MATCH_DISTANCES_BUFFER_SIZE
    value: "64"

  - name: SMPC__N_BUCKETS
    value: "10"


initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "anon-stats-server-smpcv2-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "3"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".stage.smpcv2.worldcoin.dev --query "HostedZones[0].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for anon-stats-server-smpcv2 pod",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "anon-stats-server.$PARTY_ID.stage.smpcv2.worldcoin.dev",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$POD_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"
