env:
  - name: SERVICE_NAME
    value: ampc-hnsw-continuous-rerand-2
  - name: AWS_REGION
    value: eu-north-1
  - name: PARTY_ID
    value: "2"
  - name: DB_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_HNSW_FROM_SNAPSHOT_URL
        name: application
  - name: SCHEMA_NAME
    value: SMPC_dev_2
  - name: ENVIRONMENT
    value: dev
  - name: RERAND_S3_BUCKET
    value: ampc-hnsw-continuous-rerand-store-node-2-dev
  - name: CHUNK_SIZE
    value: "2000"
  - name: CHUNK_DELAY_SECS
    value: "1"
  - name: SAFETY_BUFFER_IDS
    value: "0"
  - name: S3_POLL_INTERVAL_MS
    value: "2000"
