CREATE TABLE IF NOT EXISTS irises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 MINVALUE 1) PRIMARY KEY,
    left_code BYTEA,
    left_mask BYTEA,
    right_code BYTEA,
    right_mask BYTEA
);
