CREATE TABLE IF NOT EXISTS modifications (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 MINVALUE 1) PRIMARY KEY,
    serial_id BIGINT NOT NULL,
    request_type TEXT NOT NULL,
    s3_url TEXT,
    status TEXT NOT NULL,
    persisted BOOLEAN NOT NULL DEFAULT FALSE
);

DROP INDEX IF EXISTS idx_modifications_created_at;

DROP TABLE IF EXISTS modifications;
