CREATE TYPE IF NOT EXISTS request_status AS ENUM ('in_progress', 'completed');
CREATE TYPE IF NOT EXISTS request_type AS ENUM ('identity_deletion', 'reauth');
CREATE TABLE IF NOT EXISTS modifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    serial_id BIGINT NOT NULL,
    type request_type NOT NULL,
    s3_url TEXT,
    status request_status NOT NULL,
    persisted BOOLEAN NOT NULL DEFAULT FALSE
);
