use std::fmt;

use serde::{Deserialize, Serialize};

/// Enumeration over request processing states plus time of state change for statisitical purposes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) enum RequestStatus {
    // Associated responses have been correlated.
    Correlated,
    // Enqueued upon system ingress queue.
    Enqueued,
    // Newly generated by client.
    New,
    // Iris shares uploaded in advance of enqueuement.
    SharesUploaded,
}

impl RequestStatus {
    pub(super) const VARIANT_COUNT: usize = 4;
}

impl Default for RequestStatus {
    fn default() -> Self {
        Self::New
    }
}

impl fmt::Display for RequestStatus {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Self::Correlated => write!(f, "Correlated"),
            Self::Enqueued => write!(f, "Enqueued"),
            Self::New => write!(f, "New"),
            Self::SharesUploaded => write!(f, "SharesUploaded"),
        }
    }
}
