version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    staticcheck:
      checks:
        - all
        - -S1000
        - -SA1019
        - -SA1029
        - -ST1003
        - -ST1011

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/worldcoin)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
