# Per-node overrides; shared vars live in common-values-iris-mpc.yaml.
env:
  SMPC__SERVICE__SERVICE_NAME: "iris-mpc-1"
  SMPC__SERVER_COORDINATION__PARTY_ID: "1"
  SMPC__DB_CHUNKS_BUCKET_NAME: "iris-mpc-db-exporter-store-node-1-stage--eun1-az3--x-s3"
  SMPC__SERVICE__METRICS__PREFIX: "smpcv2-1"

initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "iris-mpc-copy-cuda-libs"
  env:
    - name: PARTY_ID
      value: "2"
    - name: MY_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".stage.smpcv2.worldcoin.dev --query "HostedZones[0].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for iris-mpc NCCL_COMM_ID",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "iris-mpc-node.$PARTY_ID.stage.smpcv2.worldcoin.dev",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$MY_NODE_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"
