apiVersion: v1
kind: Pod
metadata:
  name: db-cleaner
  namespace: iris-mpc
spec:
  hostNetwork: true
  serviceAccountName: iris-mpc  # Add this line
  securityContext:
    runAsUser: 0
  containers:
    - name: db-cleaner
      image: ubuntu
      imagePullPolicy: Always
      command: [ "/bin/bash" ]
      args: [ "-c", "while true; do ping localhost; sleep 60; done" ]
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
