apiVersion: v1
kind: Pod
metadata:
  name: secrets-tester
  namespace: iris-mpc
spec:
  serviceAccountName: iris-mpc  # Add this line
  nodeSelector:
    beta.kubernetes.io/instance-type: t3.2xlarge # Use migration node for db-cleaner
  securityContext:
    runAsUser: 0
  containers:
    - name: secrets-tester
      securityContext:
        runAsUser: 0
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault  # or Localhost if you have a local profile
      image: ubuntu
      imagePullPolicy: Always
      command: [ "/bin/bash" ]
      args: [ "-c", "while true; do ping localhost; sleep 60; done" ]
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
