env:
  - name: RUST_LOG
    value: "info"

  - name: RUST_BACKTRACE
    value: "full"

  - name: SMPC__ENVIRONMENT
    value: "stage"

  - name: SMPC__SERVICE__SERVICE_NAME
    value: "hnsw-service-1"

  - name: SMPC__PARTY_ID
    value: "1"

  - name: SMPC__MODE_OF_COMPUTE
    value: "Cpu"

  - name: SMPC__MODE_OF_DEPLOYMENT
    value: "ShadowIsolation"

  - name: SMPC__DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_MPCV2_URL
        name: application

  - name: SMPC__CPU_DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_HNSW_URL
        name: application

  - name: SMPC__MAX_DB_SIZE
    value: "2000000"
  
  - name: SMPC__CPU_DISABLE_PERSISTENCE
    value: "false"

  - name: SMPC__MATCH_DISTANCES_BUFFER_SIZE
    value: "64"

  - name: SMPC__N_BUCKETS
    value: "10"

  - name: SMPC__ENABLE_SENDING_ANONYMIZED_STATS_MESSAGE
    value: "false"

  - name: SMPC__AWS__REGION
    value: "eu-north-1"

  - name: SMPC__SERVICE_PORTS
    value: '["4000","4001","4002"]'

  - name: SMPC__HAWK_SERVER_HEALTHCHECK_PORT
    value: '3000'

  - name: SMPC__NODE_HOSTNAMES
    value: '["node.0.stage.hnsw.worldcoin.dev", "0.0.0.0", "node.2.stage.hnsw.worldcoin.dev"]'

  - name: SMPC__SHARES_BUCKET_NAME
    value: "wf-smpcv2-stage-sns-requests"

  - name: SMPC__REQUESTS_QUEUE_URL
    valueFrom:
      secretKeyRef:
        key: SQS_URL
        name: application

  - name: SMPC__RESULTS_TOPIC_ARN
    valueFrom:
      secretKeyRef:
        key: SNS_RESULTS_ARN
        name: application

  - name: SMPC__KMS_KEY_ARNS
    valueFrom:
      secretKeyRef:
        key: KMS_KEYS
        name: application

  - name: SMPC__PROCESSING_TIMEOUT_SECS
    value: "120"

  - name: SMPC__HEARTBEAT_INITIAL_RETRIES
    value: "65"

  - name: SMPC__SERVICE__METRICS__HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

  - name: SMPC__SERVICE__METRICS__PORT
    value: "8125"

  - name: SMPC__SERVICE__METRICS__QUEUE_SIZE
    value: "5000"

  - name: SMPC__SERVICE__METRICS__BUFFER_SIZE
    value: "256"

  - name: SMPC__SERVICE__METRICS__PREFIX
    value: "hnsw-1"

  - name: SMPC__IMAGE_NAME
    value: $(IMAGE_NAME)

initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "hnsw-mpc-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "1"
    - name: MY_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".stage.hnsw.worldcoin.dev --query "HostedZones[0].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for hnsw-mpc NCCL_COMM_ID",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "node.$PARTY_ID.stage.hnsw.worldcoin.dev",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$MY_NODE_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"
