env:
  - name: RUST_LOG
    value: "info"

  - name: NCCL_SOCKET_IFNAME
    value: "eth0"

  - name: NCCL_COMM_ID
    value: "iris-mpc-node.1.stage.smpcv2.worldcoin.dev:4000"

  - name: RUST_BACKTRACE
    value: "full"

  - name: SMPC__ENVIRONMENT
    value: "stage"

  - name: SMPC__SERVICE__SERVICE_NAME
    value: "smpcv2-server-stage"

  - name: SMPC__DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
        name: application

  - name: SMPC__DATABASE__MIGRATE
    value: "true"

  - name: SMPC__DATABASE__CREATE
    value: "true"

  - name: SMPC__DATABASE__LOAD_PARALLELISM
    value: "8"

  - name: SMPC__AWS__REGION
    value: "eu-north-1"

  - name: SMPC__REQUESTS_QUEUE_URL
    valueFrom:
      secretKeyRef:
        key: SQS_URL
        name: application

  - name: SMPC__RESULTS_TOPIC_ARN
    valueFrom:
      secretKeyRef:
        key: SNS_RESULTS_ARN
        name: application

  - name: SMPC__PROCESSING_TIMEOUT_SECS
    value: "60"

  - name: SMPC__PATH
    value: "/data/"

  - name: SMPC__KMS_KEY_ARNS
    valueFrom:
      secretKeyRef:
        key: KMS_KEYS
        name: application

  - name: SMPC__PARTY_ID
    value: "0"

  - name: SMPC__PUBLIC_KEY_BASE_URL
    value: "https://pki-smpcv2-stage.worldcoin.org"

  - name: SMPC__CLEAR_DB_BEFORE_INIT
    value: "true"

  - name: SMPC__INIT_DB_SIZE
    value: "0"

  - name: SMPC__MAX_DB_SIZE
    value: "1000000"

  - name: SMPC__MAX_BATCH_SIZE
    value: "64"

initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "iri-mpc-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "1"
    - name: MY_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".stage.smpcv2.worldcoin.dev --query "HostedZones[].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for iris-mpc NCCL_COMM_ID",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "iris-mpc-node.$PARTY_ID.stage.smpcv2.worldcoin.dev",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$MY_NODE_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"

      cd /libs
      aws s3 cp s3://wf-smpcv2-stage-libs/libcublas.so.12.2.5.6 .
      aws s3 cp s3://wf-smpcv2-stage-libs/libcublasLt.so.12.2.5.6 .
