image: "ghcr.io/worldcoin/iris-mpc:v0.4.9"

environment: stage
replicaCount: 1

strategy:
  type: Recreate

datadog:
  enabled: true

ports:
  - containerPort: 8000
    name: upgradeprotocol
    protocol: TCP
  - containerPort: 3000
    name: health
    protocol: TCP

livenessProbe:
  httpGet:
    path: /health
    port: health

readinessProbe:
  periodSeconds: 30
  failureThreshold: 10
  httpGet:
    path: /health
    port: health

resources:
  limits:
    cpu: 4
    memory: 1Gi
  requests:
    cpu: 4
    memory: 1Gi

imagePullSecrets:
  - name: github-secret

nodeSelector:
  kubernetes.io/arch: amd64

hostNetwork: true

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534

serviceAccount:
  create: true

command: [ "/bin/upgrade-server" ]

env:
  - name: SMPC__DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
        name: application


keelPolling:
  # -- Specifies whether keel should poll for container updates
  enabled: true

serverTargetPort: upgradeprotocol

ingress:
  enabled: true

ingressRouteTCP:
  enabled: true
  entryPoints:
    - websecure
  services:
    - name: upgrade-server
      port: 80
      targetPort: upgradeprotocol
