image: "ghcr.io/worldcoin/rerandomization-protocol:4161e46ca376d391c52139bd1b1d56ca420c1072"
replicaCount: 1

environment: stage

command: ["/bin/rerandomize-db"]
args:
  - "rerandomize-continuous"

strategy:
  type: Recreate

serviceAccount:
  create: true
  name: "iris-mpc-continuous-rerandomization"

datadog:
  enabled: true

ports:
  - containerPort: 3000
    name: health
    protocol: TCP

startupProbe:
  httpGet:
    path: /health
    port: health

livenessProbe:
  httpGet:
    path: /health
    port: health

readinessProbe:
  periodSeconds: 20
  failureThreshold: 4
  httpGet:
    path: /health
    port: health

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534

imagePullSecrets:
  - name: github-secret

resources:
  limits:
    cpu: 3.5
    memory: 12Gi
  requests:
    cpu: 3.5
    memory: 12Gi

nodeSelector:
  kubernetes.io/arch: amd64
  workload: "continuous_rerandomization"

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "continuousDbRerandomization"
    effect: "NoSchedule"

concurrencyPolicy: Replace
