image: "ghcr.io/worldcoin/gpu-iris-mpc:f109fbc55dcd985ecf708e4255a665a5e5f616e5"

environment: stage
replicaCount: 1

strategy:
  type: Recreate

datadog:
  enabled: false

ports:
  - containerPort: 3000
    name: http
    protocol: TCP

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

resources:
  limits:
    cpu: 31
    memory: 120Gi
    nvidia.com/gpu: 1
    vpc.amazonaws.com/efa: 1
  requests:
    cpu: 30
    memory: 110Gi
    nvidia.com/gpu: 1
    vpc.amazonaws.com/efa: 1

imagePullSecrets:
  - name: github-secret

nodeSelector:
  kubernetes.io/arch: amd64

hostNetwork: true

podSecurityContext:
  runAsUser: 65534
  runAsGroup: 65534

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "gpuGroup"
    effect: "NoSchedule"
