env:
  - name: ENV
    value: stage
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_HNSW_URL
        name: application
  - name: SERVICE_NAME
    value: ampc-hnsw-db-exporter-2
  - name: AWS_REGION
    value: eu-north-1
  - name: GIN_MODE
    value: release
  - name: EXPORT_S3_BUCKET_NAME
    value: "ampc-hnsw-db-exporter-store-node-2-stage--eun1-az3--x-s3"
  - name: NODE_ID
    value: "2"

attachSecurityGroupPolicy:
  enabled: true
  groupIds:
    - sg-029d495666e5f0780 # smpc2-stage ampc-hnsw-db-exporter pod sg
