resources:
  limits:
    cpu: 96
    memory: 1100Gi
    nvidia.com/gpu: 8
    hugepages-2Mi: 5Gi
    vpc.amazonaws.com/efa: 4
  requests:
    cpu: 94
    memory: 1000Gi
    nvidia.com/gpu: 8
    hugepages-2Mi: 5Gi
    vpc.amazonaws.com/efa: 4

env:
  - name: RUST_LOG
    value: "info"

  - name: NCCL_SOCKET_IFNAME
    value: "eth"

  - name: FI_EFA_USE_DEVICE_RDMA
    value: "1"

  - name: NCCL_COMM_ID
    value: "iris-mpc-node-eu-central-1.1.stage.smpcv2.worldcoin.dev:4000"

  - name: RUST_BACKTRACE
    value: "full"

  - name: SMPC__ENVIRONMENT
    value: "stage"

  - name: SMPC__SERVICE__SERVICE_NAME
    value: "iris-mpc-0"

  - name: SMPC__DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_AURORA_URL
        name: application

  - name: SMPC__DATABASE__MIGRATE
    value: "true"

  - name: SMPC__DATABASE__CREATE
    value: "true"

  - name: SMPC__DATABASE__LOAD_PARALLELISM
    value: "8"

  - name: SMPC__AWS__REGION
    value: "eu-central-1"

  - name: SMPC__REQUESTS_QUEUE_URL
    valueFrom:
      secretKeyRef:
        key: SQS_URL
        name: application

  - name: SMPC__RESULTS_TOPIC_ARN
    valueFrom:
      secretKeyRef:
        key: SNS_RESULTS_ARN
        name: application

  - name: SMPC__PROCESSING_TIMEOUT_SECS
    value: "120"
  
  - name: SMPC__HEARTBEAT_INITIAL_RETRIES
    value: "65"

  - name: SMPC__PATH
    value: "/data/"

  - name: SMPC__KMS_KEY_ARNS
    valueFrom:
      secretKeyRef:
        key: KMS_KEYS
        name: application

  - name: SMPC__PARTY_ID
    value: "0"

  - name: SMPC__PUBLIC_KEY_BASE_URL
    value: "https://pki-smpcv2-stage.worldcoin.org"

  - name: SMPC__SHARES_BUCKET_NAME
    value: "wf-smpcv2-stage-sns-requests"

  - name: SMPC__ENABLE_S3_IMPORTER
    value: "false"

  - name: SMPC__DB_CHUNKS_BUCKET_NAME
    value: "iris-mpc-db-exporter-store-node-0-stage--eun1-az3--x-s3"

  - name: SMPC__DB_CHUNKS_FOLDER_NAME
    value: "even_odd_binary_output_16k"

  - name: SMPC__LOAD_CHUNKS_PARALLELISM
    value: "64"

  - name: SMPC__LOAD_CHUNKS_BUFFER_SIZE
    value: "1024"

  - name: SMPC__CLEAR_DB_BEFORE_INIT
    value: "true"

  - name: SMPC__INIT_DB_SIZE
    value: "1000"

  - name: SMPC__MAX_DB_SIZE
    value: "1300000"

  - name: SMPC__MAX_BATCH_SIZE
    value: "64"

  - name: SMPC__MATCH_DISTANCES_BUFFER_SIZE
    value: "64"

  - name: SMPC__N_BUCKETS
    value: "10"

  - name: SMPC__ENABLE_SENDING_ANONYMIZED_STATS_MESSAGE
    value: "true"

  - name: SMPC__ENABLE_REAUTH
    value: "true"

  - name: SMPC__ENABLE_RESET
    value: "true"

  - name: SMPC__LUC_ENABLED
    value: "false"

  - name: SMPC__LUC_LOOKBACK_RECORDS
    value: "50"

  - name: SMPC__LUC_SERIAL_IDS_FROM_SMPC_REQUEST
    value: "true"

  - name: SMPC__SERVICE__METRICS__HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

  - name: SMPC__SERVICE__METRICS__PORT
    value: "8125"

  - name: SMPC__SERVICE__METRICS__QUEUE_SIZE
    value: "5000"

  - name: SMPC__SERVICE__METRICS__BUFFER_SIZE
    value: "256"

  - name: SMPC__SERVICE__METRICS__PREFIX
    value: "smpcv2-0"

  - name: SMPC__RETURN_PARTIAL_RESULTS
    value: "true"

  - name: SMPC__NODE_HOSTNAMES
    value: '["iris-mpc-node-eu-central-1.1.stage.smpcv2.worldcoin.dev","iris-mpc-node-eu-central-1.2.stage.smpcv2.worldcoin.dev","iris-mpc-node-eu-central-1.3.stage.smpcv2.worldcoin.dev"]'

  - name: SMPC__IMAGE_NAME
    value: $(IMAGE_NAME)

  - name: SMPC__ENABLE_SYNC_QUEUES_ON_SNS_SEQUENCE_NUMBER
    value: "true"

  - name: SMPC__ENABLE_MODIFICATIONS_SYNC
    value: "true"

  - name: SMPC__ENABLE_MODIFICATIONS_REPLAY
    value: "true"
  
  - name : SMPC__ENABLE_DEBUG_TIMING
    value: "true"

initContainer:
  enabled: true
  image: "amazon/aws-cli:2.17.62"
  name: "iri-mpc-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "1"
    - name: MY_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  configMap:
    init.sh: |
      #!/usr/bin/env bash

      # Set up environment variables
      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".stage.smpcv2.worldcoin.dev --query "HostedZones[0].Id" --output text)

      # Generate the JSON content in memory
      BATCH_JSON=$(cat <<EOF
      {
        "Comment": "Upsert the A record for iris-mpc NCCL_COMM_ID",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "iris-mpc-node-eu-central-1.$PARTY_ID.stage.smpcv2.worldcoin.dev",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "$MY_NODE_IP"
              }]
            }
          }
        ]
      }
      EOF
      )

      # Execute AWS CLI command with the generated JSON
      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch "$BATCH_JSON"

      # region is set to eu-north-1 beacause the bucket is in that region
      cd /libs
      aws s3 cp --region eu-north-1 s3://wf-smpcv2-stage-libs/libcublas.so.12.2.5.6 .
      aws s3 cp --region eu-north-1 s3://wf-smpcv2-stage-libs/libcublasLt.so.12.2.5.6 .
