#!/usr/bin/env bash

# ###############################################################
# PATH
# ###############################################################

# Set path -> here.
_HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ###############################################################
# COMMANDS
# ###############################################################

alias hnsw-service-client-exec='source $_HERE/exec.sh'
alias hnsw-service-client-init='source $_HERE/init.sh'
alias hnsw-service-client-set-env='source $_HERE/set_env.sh'
