#!/usr/bin/env bash

# ###############################################################
# PATH
# ###############################################################

# Set path -> here.
export _SC_HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# ###############################################################
# COMMANDS
# ###############################################################

alias hnsw-service-client-exec='source $_SC_HERE/exec.sh'
alias hnsw-service-client-init='source $_SC_HERE/init.sh'
alias hnsw-service-client-set-env='source $_SC_HERE/set_env.sh'
