image: "ghcr.io/worldcoin/gpu-iris-mpc:f109fbc55dcd985ecf708e4255a665a5e5f616e5"

env:
  - name: SMPC__ENVIRONMENT
    value: "stage"

  - name: SMPC__SERVICE__SERVICE_NAME
    value: "smpcv2-server"

  - name: SMPC__DATABASE__URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
        name: application

  - name: SMPC__DATABASE__MIGRATE
    value: "true"

  - name: SMPC__DATABASE__CREATE
    value: "true"

  - name: SMPC__AWS__REGION
    value: "eu-north-1"

  - name: SMPC__SERVERS__CODES_ENGINE_PORT
    value: "4000"

  - name: SMPC__SERVERS__MASKS_ENGINE_PORT
    value: "4001"

  - name: SMPC__SERVERS__BATCH_CODES_ENGINE_PORT
    value: "4002"

  - name: SMPC__SERVERS__BATCH_MASKS_ENGINE_PORT
    value: "4003"

  - name: SMPC__SERVERS__PHASE_2_BATCH_PORT
    value: "4004"

  - name: SMPC__SERVERS__PHASE_2_PORT
    value: "4005"

  - name: SMPC__PARTY_ID
    value: "2"

  - name: SMPC__REQUESTS_QUEUE_URL
    valueFrom:
      secretKeyRef:
        key: SQS_URL
        name: application

  - name: SMPC__RESULTS_TOPIC_ARN
    valueFrom:
      secretKeyRef:
        key: SNS_RESULTS_ARN
        name: application

  - name: SMPC__PATH
    value: "/data/"

# added by terraform do not change
#  - name: SMPC__KMS_KEY_IDS
#    value: ''
