args:
  - "--bind-addr"
  - "0.0.0.0:8000"
  - "--db-url"
  - "$(SMPC__DATABASE__URL)"
  - "--party-id"
  - "2"
  - "--eye"
  - "left"
  - "--environment"
  - "$(ENVIRONMENT)"
  - "--threads"
  - "1"
  - "--batch-size"
  - "50"
