args:
  - "--bind-addr"
  - "0.0.0.0:8000"
  - "--db-url"
  - "$(SMPC__DATABASE__URL)"
  - "--party-id"
  - "2"
  - "--eye"
  - "left"
  - "--environment"
  - "$(ENVIRONMENT)"
  - "--batch-size"
  - "50"

initContainer:
  enabled: true
  name: "upgrade-proto-dns-records-updater"
  env:
    - name: PARTY_ID
      value: "3"
    - name: SIDE
      value: left
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  configMap:
    batch.json.tpl: |
      {
        "Comment": "Upsert the A record for upgrade-server",
        "Changes": [
          {
            "Action": "UPSERT",
            "ResourceRecordSet": {
              "Name": "%%DOMAIN%%",
              "TTL": 5,
              "Type": "A",
              "ResourceRecords": [{
                "Value": "%%POD_IP%%"
              }]
            }
          }
        ]
      }
    init.sh: |
      #!/usr/bin/env bash

      HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$PARTY_ID".stage.smpcv2.worldcoin.dev --query "HostedZones[].Id" --output text)

      sed "s/%%POD_IP%%/$MY_POD_IP/" batch.json.tpl > batch.json.tmp
      sed "s/%%DOMAIN%%/upgrade-$SIDE.$PARTY_ID.stage.smpcv2.worldcoin.dev/" batch.json.tmp > batch.json

      aws route53 change-resource-record-sets --hosted-zone-id "$HOSTED_ZONE_ID" --change-batch file://batch.json
