name: Build and push image for iris-mpc-db-exporter

on:
  release:
    types:
      - "published"
  push:
    branches:
      - "ertugrulaypek/pop-3534-migrate-iris-mpc-db-exporter-to-iris-mpc-repo"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: false

env:
  ENV: CI
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}-db-exporter"
  SERVICE_NAME: iris-mpc-db-exporter

jobs:
  docker:
    runs-on:
      labels: ubuntu-22.04-16core
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global url."https://${{ secrets.GIT_HUB_TOKEN }}:x-oauth-basic@github.com/worldcoin/".insteadOf "https://github.com/worldcoin/"
      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version-file: 'iris-mpc-db-exporter/go.mod'
      - name: Compile binary
        working-directory: iris-mpc-db-exporter
        run: CGO_ENABLED=1 go build -buildvcs=false -o ${{ env.SERVICE_NAME }} -ldflags="-extldflags=-static"
      - name: Build and Push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: iris-mpc-db-exporter
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ github.event_name == 'release' && format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE_NAME, github.event.release.tag_name) || '' }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
